Fix missing ignore_build_queue attribute
Executing `_fn_fetch` directly without supplying `args` could lead to
an error like this:

```
AttributeError: 'Namespace' object has no attribute 'ignore_build_queue'
```

This is now fixed.

Change-Id: Icccb20f247c12a2e0407f796f9b2124cb5192fdb